### ISSUE TITLE
Missing Attribute ColorUsage

### ISSUE THREAD

**Issue by dantreble** [keijiro/KvantSpray#1]
Assets/Kvant/Spray/Spray.cs(57,10): error CS0246: The type or namespace name `ColorUsage' could not be found. Are you missing a using directive or an assembly reference?

It compiles and runs fine without it. It's awesome!

**Comment by babelchips** [comment]
Same issue.  Assets/Kvant/Spray/Spray.cs(57,10): error CS0246: The type or namespace name `ColorUsage' could not be found. Are you missing a using directive or an assembly reference?

**Comment by wuxingogo** [comment]
The type or namespace name 'ShadowCastingMode' could not be found.

**Comment by keijiro** [comment]
ColorUsage is a newly added attribute in Unity 5.1. Please verify it on 5.1.0.
https://unity3d.com/unity/beta
