### ISSUE TITLE
mesh.Optimize() obsolete

### ISSUE THREAD

**Issue by nguyenngocthanhson129** [keijiro/KvantSpray#12]
Hi Keijiro,
In Unity 2017.1 mesh.Optimize() function in BulkMesh.cs return error because this method is no longer supported (UnityUpgradable). Please help me fix it.
Thanks.

**Comment by Alverik** [comment]
Errors marked as (UnityUpgradable) are usually upgraded by Unity automatically when Unity starts. I'm using KvantSpray in Unity2017.2 and it works fine. Some other errors may be stopping the upgrade process or you simply need to restart Unity again and let it do the work.

**Comment by keijiro** [comment]
...or you can use KvantSprayMV instead.

https://github.com/keijiro/KvantSprayMV

**Comment by nguyenngocthanhson129** [comment]
Thanks, I'll try it.
