### ISSUE TITLE
particle created event

### ISSUE THREAD

**Issue by preamptive** [keijiro/KvantSpray#14]
I want to send an osc message every time a particle is created but it i cant figure out where to put my code. I presume because the particles are generated within the buffer and shader?

Could you possibly explain where each particle gets created within your code? Sorry as you can probalby tell I only have a basic understanding of your code.

Thanks

Keith

**Comment by keijiro** [comment]
Here: https://github.com/keijiro/KvantSpray/blob/master/Assets/Kvant/Spray/Shaders/Kernel.shader#L61

Basically the life cycle of particles are controlled within the shader, so it's not directly accessible from CPU code (scripts). It will require sacrificing performance to feedback information from GPU to CPU.

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen for further questions.
