### ISSUE TITLE
Setting position and color for each particle

### ISSUE THREAD

**Issue by akashcastelino** [keijiro/KvantSpray#15]
Hi,

Thanks for the great repo!

I have a question about whether it is possible by script to set each spray particle's position and color ?

**Comment by sergiobd** [comment]
From my exploration of the repo, positions and velocities are baked in a texture. So you would not be able to set each particles position from a script unless you bake everything on a texture and pass it to the gpu.

**Comment by keijiro** [comment]
@sergiobd is right. It's quite hard to modify them in a performant way.

**Comment by akashcastelino** [comment]
Hi thanks for your answers! 
I shall close this
