### ISSUE TITLE
Error in all three shaders: "cannot map expression to vs_4_0 instruction set"

### ISSUE THREAD

**Issue by Podden** [keijiro/KvantSpray#2]
The error points to this line in the Vertex Shader:
float4 r = tex2D(_RotationTex, uv);

**Comment by Podden** [comment]
found an old pos from unity's Aras: http://forum.unity3d.com/threads/how-to-use-vertex-texture-fetch.63231/
and changing the two fines in
float4 p = tex2Dlod(_PositionTex, v.texcoord);
float4 r = tex2Dlod(_RotationTex, v.texcoord);
works but you loose the buffer offset

**Comment by keijiro** [comment]
Fixed. Thank you for reporting.
