### ISSUE TITLE
Particles disappear if gameobject is out of cameraview frustrum

### ISSUE THREAD

**Issue by Podden** [keijiro/KvantSpray#3]
headline basicly says everything :). Is there a way to stop Unity from culling the object?

**Comment by sp4ghet** [comment]
http://docs.unity3d.com/460/Documentation/Manual/OcclusionCulling.html

maybe unset spray as a culling target object

**Comment by Podden** [comment]
Nope, it's not occlusion culling, but frustrum culling (object's out of camera frustrum) and you have no influence on that as far as i know. A solution for this I found is setting the mesh bounds of the particle "mesh" programmaticly to be all around the camera.
