### ISSUE TITLE
build to iOS not work

### ISSUE THREAD

**Issue by nvcken** [keijiro/KvantSpray#7]
I tried to run on iphone, but just get a initial Unity 3d screen only, not see any particles

What I'm wrong?

**Comment by keijiro** [comment]
Please see the system requirements :)

**Comment by nvcken** [comment]
I tried build to OS X x86_64 but just get a blank init Unity scene, please help.

**Comment by keijiro** [comment]
Okay! Then, could you send a small project that can reproduce the issue you met?

**Comment by nvcken** [comment]
Sent to your mail, please help.
Thanks

**Comment by keijiro** [comment]
Thanks for sending the project. However, I can't reproduce the issue. I added some of the test scenes to the Scenes In Build list and built the project. Then, it works.

Is there any special steps needed to reproduce the issue?

**Comment by nvcken** [comment]
okay, I'll try double check again.
I think my mistake.
Thanks for your help
